wandb_version: 1

exp_name:
  desc: null
  value: madql_uav_dynamic_user
seed:
  desc: null
  value: 1
torch_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: true
wandb_track:
  desc: null
  value: true
wandb_name:
  desc: null
  value: UAV_Subband_Allocation_DQN_Pytorch_Dynamic
wandb_entity:
  desc: null
  value: null
env_id:
  desc: null
  value: ma-custom-UAV-connectivity
num_env:
  desc: null
  value: 1
num_episode:
  desc: null
  value: 800
num_steps:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.00035
gamma:
  desc: null
  value: 0.95
batch_size:
  desc: null
  value: 512
epsilon:
  desc: null
  value: 0.1
update_rate:
  desc: null
  value: 10
buffer_size:
  desc: null
  value: 125000
epsilon_min:
  desc: null
  value: 0.1
epsilon_decay:
  desc: null
  value: false
epsilon_decay_steps:
  desc: null
  value: 1
info_exchange_lvl:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    code_path: code/dynamic_env/main.py
    python_version: 3.10.4
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681873898.730539
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      - 35
      4: 3.10.4
      5: 0.14.2
      8:
      - 3
      - 5
