wandb_version: 1

exp_name:
  desc: null
  value: madql_uav
seed:
  desc: null
  value: 1
torch_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: true
wandb_track:
  desc: null
  value: true
wandb_name:
  desc: null
  value: UAV_Subband_Allocation_DQN_Pytorch
wandb_entity:
  desc: null
  value: null
env_id:
  desc: null
  value: ma-custom-UAV-connectivity
num_env:
  desc: null
  value: 1
num_episode:
  desc: null
  value: 2000
num_steps:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.00025
gamma:
  desc: null
  value: 0.95
batch_size:
  desc: null
  value: 512
epsilon:
  desc: null
  value: 0.1
update_rate:
  desc: null
  value: 10
buffer_size:
  desc: null
  value: 125000
epsilon_min:
  desc: null
  value: 0.1
epsilon_decay:
  desc: null
  value: false
epsilon_decay_steps:
  desc: null
  value: 1
info_exchange_lvl:
  desc: null
  value: 2
num_user:
  desc: null
  value: 100
num_uav:
  desc: null
  value: 5
generate_user_distribution:
  desc: null
  value: false
carrier_freq:
  desc: null
  value: 2
coverage_xy:
  desc: null
  value: 1000
uav_height:
  desc: null
  value: 350
theta:
  desc: null
  value: 60
bw_uav:
  desc: null
  value: 4000000.0
bw_rb:
  desc: null
  value: 180000.0
grid_space:
  desc: null
  value: 100
uav_dis_th:
  desc: null
  value: 500
dist_pri_param:
  desc: null
  value: 0.2
_wandb:
  desc: null
  value:
    code_path: code/main.py
    python_version: 3.10.4
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682920315.376677
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      - 35
      4: 3.10.4
      5: 0.14.2
      8:
      - 3
      - 5
